export const CHECK_USER_REGISTRETED = 'CHECK_USER_REGISTRETED'
export const GET_USERS = 'GET_USERS'
export const SET_IS_BUTTON_DISABLED = 'SET_IS_BUTTON_DISABLED'
export const SET_IS_BUTTON_IS_ABLED = 'SET_IS_BUTTON_IS_ABLED'
// export const SET_IS_ERROR = 'SET_IS_ERROR'

