// export const SET_NAME = 'SET_NAME'
// export const SET_SURNAME = 'SET_SURNAME'
// export const SET_EMAIL = 'SET_EMAIL'
// export const SET_PASSWORD =  'SET_PASSWORD'
export const SET_USER =  'SET_USER'
export const GET_USERS = 'GET_USERS'